from clarity.database.in_memory_db.tag_item import Tag_item
from clarity.database.in_memory_db.storage_item import Storage_item
from clarity.database.in_memory_db.folder_item import Folder_item
from clarity.database.in_memory_db.file_item import File_item

class Initialize_data():
    

    def init_tags(self, td):
        td.add_tag("holiday", [])
        td.add_tag("snow", [])
        td.add_tag("water", [])
        td.add_tag("ocean", [td.return_tag("water")])
        td.add_tag("picture", [])
        td.add_tag("germany", [])
        ger_tag = td.return_tag("germany")
        td.add_tag("france", [])
        fr_tag = td.return_tag("france")
        td.add_tag("austria", [])
        au_tag = td.return_tag("austria")
        td.add_tag("zillertal", [au_tag])
        td.add_tag("ski",[])
        td.add_tag("surfing",[])
        td.add_tag("biarritz", [fr_tag])
        td.add_tag("blackforest", [ger_tag])
        td.add_tag("greifswald", [ger_tag])
        td.add_tag("year", [])
        year_tag = td.return_tag("year")
        td.add_tag("month", [])
        month_tag = td.return_tag("month")
        td.add_tag("2016", [year_tag])
        td.add_tag("2017", [year_tag])
        td.add_tag("2018", [year_tag])
        td.add_tag("2019", [year_tag])
        td.add_tag("1999", [year_tag])
        td.add_tag("january", [month_tag])
        td.add_tag("february", [month_tag])
        td.add_tag("march", [month_tag])
        td.add_tag("april", [month_tag])
        td.add_tag("may", [month_tag])
        td.add_tag("june", [month_tag])
        td.add_tag("july", [month_tag])
        td.add_tag("august", [month_tag])
        td.add_tag("september", [month_tag])
        td.add_tag("october", [month_tag])
        td.add_tag("november", [month_tag])
        td.add_tag("december", [month_tag])
        td.add_tag("program", [])
        td.add_tag("music", [])
        td.add_tag("music_player", [])
        td.add_tag("network_tool", [])
        td.add_tag("game", [])
        td.add_tag("microsoft_game_studios", [])
        td.add_tag("programming", [])
        td.add_tag("university", [])
        td.add_tag("lecture", [])
        td.add_tag("project", [])
        td.add_tag("hackaton", [])
        td.add_tag("hacktival", [td.return_tag("hackaton"), td.return_tag("programming")])
        td.add_tag("programming_language", [])
        pl_tag = td.return_tag("programming_language")
        td.add_tag("python", [pl_tag])
        td.add_tag("c++", [pl_tag])
        td.add_tag("c", [pl_tag])
        td.add_tag("c#", [pl_tag])
        td.add_tag("java", [pl_tag])
        td.add_tag("rust", [pl_tag])
        td.add_tag("jscript", [pl_tag])
        td.add_tag("html", [pl_tag])
        td.add_tag("data_base", [])
        db_tag = td.return_tag("data_base")
        td.add_tag("key_value_db", [db_tag])
        td.add_tag("fun_db", [db_tag])
        td.add_tag("lazy_db", [db_tag])
        td.add_tag("couch_db", [db_tag])
        td.add_tag("fantasy_db", [db_tag])
        td.add_tag("search_db", [db_tag])
        
    def init_storage_items(self, fd, td):
        fd.add_file("snow01.jpg", "files", [td.return_tag("blackforest"), td.return_tag("december"), td.return_tag("2018"), td.return_tag("snow"), td.return_tag("picture")])
        fd.add_file("snow02.jpg", "files", [td.return_tag("blackforest"), td.return_tag("march"), td.return_tag("2018"), td.return_tag("snow"), td.return_tag("picture")])
        fd.add_file("snow03.jpg", "files", [td.return_tag("blackforest"), td.return_tag("february"), td.return_tag("2018"), td.return_tag("snow"), td.return_tag("picture")])
        fd.add_file("snow04.jpg", "files", [td.return_tag("zillertal"), td.return_tag("november"), td.return_tag("2019"), td.return_tag("snow"), td.return_tag("picture"), td.return_tag("ski"), td.return_tag("holiday")])
        fd.add_file("snow05.jpg", "files", [td.return_tag("zillertal"), td.return_tag("january"), td.return_tag("2019"), td.return_tag("snow"), td.return_tag("picture"), td.return_tag("ski"), td.return_tag("holiday")])
        fd.add_file("snow06.jpg", "files", [td.return_tag("zillertal"), td.return_tag("april"), td.return_tag("2019"), td.return_tag("snow"), td.return_tag("picture"), td.return_tag("ski"), td.return_tag("holiday")])
        fd.add_file("surfing01.jpg", "files", [td.return_tag("biarritz"), td.return_tag("june"), td.return_tag("2017"), td.return_tag("ocean"), td.return_tag("picture"), td.return_tag("surfing"), td.return_tag("holiday")])
        fd.add_file("surfing02.jpg", "files", [td.return_tag("biarritz"), td.return_tag("july"), td.return_tag("2017"), td.return_tag("ocean"), td.return_tag("picture"), td.return_tag("surfing"), td.return_tag("holiday")])
        fd.add_file("surfing03.jpg", "files", [td.return_tag("biarritz"), td.return_tag("may"), td.return_tag("2017"), td.return_tag("ocean"), td.return_tag("picture"), td.return_tag("surfing"), td.return_tag("holiday")])
        fd.add_file("visiting01.jpg", "files", [td.return_tag("greifswald"), td.return_tag("august"), td.return_tag("2018"), td.return_tag("water"), td.return_tag("picture"), td.return_tag("holiday")])
        fd.add_file("visiting02.jpg", "files", [td.return_tag("greifswald"), td.return_tag("september"), td.return_tag("2019"), td.return_tag("water"), td.return_tag("picture"), td.return_tag("holiday")])
        fd.add_file("visiting03.jpg", "files", [td.return_tag("greifswald"), td.return_tag("october"), td.return_tag("2018"), td.return_tag("water"), td.return_tag("picture"), td.return_tag("holiday")])
        fd.add_folder("cch", "files", [td.return_tag("february"), td.return_tag("programming"), td.return_tag("university"), td.return_tag("2019"), td.return_tag("c++"), td.return_tag("project"), td.return_tag("march")])
        fd.add_folder("ch", "files", [td.return_tag("january"), td.return_tag("programming"), td.return_tag("university"), td.return_tag("2019"), td.return_tag("c++"), td.return_tag("project")])
        fd.add_folder("smartxplore", "files", [td.return_tag("may"), td.return_tag("programming"), td.return_tag("hacktival"), td.return_tag("2019"), td.return_tag("python"), td.return_tag("project"), td.return_tag("data_base")])
        fd.add_folder("age_of_empires_2", "files", [td.return_tag("may"), td.return_tag("game"), td.return_tag("1999"), td.return_tag("microsoft_game_studios")])
        fd.add_folder("vlc", "files", [td.return_tag("program"), td.return_tag("music_player"), td.return_tag("music")])
        fd.add_folder("media_player", "files", [td.return_tag("may"), td.return_tag("program"), td.return_tag("programming"), td.return_tag("java"), td.return_tag("2016"), td.return_tag("project"), td.return_tag("music_player")])
        fd.add_folder("drone_controls", "files", [td.return_tag("may"), td.return_tag("program"), td.return_tag("programming"), td.return_tag("c#"), td.return_tag("2019"), td.return_tag("hacktival"), td.return_tag("project")])
        fd.add_folder("putty", "files", [td.return_tag("program"), td.return_tag("network_tool")])
        